openapi: 3.0.0
info:
  title: TBP API
  version: '1.0'
  contact: {}
  description: TBP Core API
servers:
  - url: 'http://localhost:3000'
paths:
  '/bots/{botID}/messages':
    get:
      summary: List messages
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Message'
                required:
                  - data
      operationId: get-bot-messages
      description: List messages for a bot identified by botID
      parameters: []
    parameters:
      - schema:
          type: string
          format: uuid
        name: botID
        in: path
        required: true
  '/bots/{botID}/userattributes':
    parameters:
      - schema:
          type: string
          format: uuid
        name: botID
        in: path
        required: true
    get:
      summary: Bot user attribute list
      tags: []
      operationId: get-bot-userattributes
      description: List user attributes for a bot
      parameters: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserAttribute'
                required:
                  - data
              examples: {}
    post:
      summary: Bot user attribute create
      operationId: create-bot-userattribute
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UserAttribute'
              examples: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/NewUserAttribute'
            examples: {}
      description: Create user attribute for a bot
  '/bots/{botID}/userattributes/{userattributeID}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: botID
        in: path
        required: true
      - schema:
          type: string
          format: uuid
        name: userattributeID
        in: path
        required: true
    get:
      summary: Get  user attribute value for a user
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/UserAttribute'
                required:
                  - data
      operationId: get-userattribute-for-user
      description: Get the value of a user attribute for a given user
      parameters:
        - schema:
            type: string
          in: query
          name: user
          description: 'user identifier (email, external ID)'
    post:
      summary: Set a user attribute value for a user
      operationId: set-userattribute-for-user
      responses:
        '200':
          description: OK
      description: Set the value of a user attribute for a given user
      requestBody:
        content:
          application/vnd.api+json:
            schema:
              type: object
      parameters: []
  /activity:
    post:
      summary: Create activity
      operationId: activity-create
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Activity'
                required:
                  - data
              examples: {}
      description: Send a CMS message to a given user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/NewActivity'
              required:
                - data
            examples: {}
        description: ''
    parameters: []
  '/bots/{botID}/users/{userID}/state/{userAttributeID}':
    parameters:
      - schema:
          type: string
          format: uuid
        name: botID
        in: path
        required: true
      - schema:
          type: string
        name: userID
        in: path
        required: true
      - schema:
          type: string
        name: userAttributeID
        in: path
        required: true
    patch:
      summary: ''
      operationId: patch-bots-botID-users-userID-state-userAttributeId
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
                required:
                  - value
      description: '#WIP'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  type: string
              required:
                - value
  /bots:
    get:
      summary: Bot list
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Bot'
                required:
                  - data
      operationId: bot-list
      description: Grabs a list of bots for the authenticated token (constrainted by the bots selected during consent)
    parameters: []
  '/bots/{botID}/analytics':
    parameters:
      - schema:
          type: string
          format: uuid
        name: botID
        in: path
        required: true
    get:
      summary: Bot analytics
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties: false
                properties:
                  data:
                    type: array
                    uniqueItems: false
                    maxItems: 7
                    minItems: 5
                    items:
                      $ref: '#/components/schemas/Metric'
                required:
                  - data
              examples: {}
      operationId: get-bot-analytics
      parameters:
        - schema:
            type: string
            format: date
            example: '2020-11-21'
          in: query
          name: date
          required: true
      description: Return top-line analytics for a given date
  /activity/external:
    post:
      summary: ''
      operationId: activity-external-create
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/ExternalActivity'
                required:
                  - data
              examples: {}
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  $ref: '#/components/schemas/NewExternalActivity'
              required:
                - data
            examples: {}
      description: Send a raw payload message to a given user
components:
  schemas:
    Message:
      title: Message
      type: object
      description: Message
      x-examples: {}
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - message
        attributes:
          type: object
          required:
            - name
          properties:
            name:
              type: string
              example: Welcome Message
            parts:
              type: array
              items:
                type: object
                properties:
                  type:
                    type: string
                    enum:
                      - text
                  text:
                    type: string
                    example: Welcome to the experience
                  buttons:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - postback
                            - open_url
                        title:
                          type: string
                          example: Click me to start
                        actions:
                          type: array
                          items:
                            type: object
                            properties:
                              type:
                                type: string
                                enum:
                                  - send_message
                              id:
                                type: string
                                format: uuid
                            required:
                              - type
                              - id
                      required:
                        - type
                        - title
                required:
                  - type
      required:
        - id
        - type
        - attributes
    UserAttribute:
      title: UserAttribute
      description: User attribute
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
          required:
            - id
        - $ref: '#/components/schemas/NewUserAttribute'
      x-examples: {}
    NewUserAttribute:
      title: NewUserAttribute
      type: object
      x-examples: {}
      properties:
        type:
          type: string
          enum:
            - userattribute
        attributes:
          type: object
          required:
            - name
          properties:
            name:
              type: string
            is_pii:
              type: boolean
      required:
        - type
        - attributes
    NewActivity:
      title: NewActivity
      type: object
      x-examples: {}
      properties:
        type:
          type: string
          default: activities
          enum:
            - activity
        attributes:
          type: object
          required:
            - recipient
            - from
            - message
          properties:
            recipient:
              type: string
            from:
              type: string
              format: uuid
            message:
              type: string
              format: uuid
      required:
        - type
        - attributes
    Activity:
      title: Activity
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
          required:
            - id
        - $ref: '#/components/schemas/NewActivity'
      x-examples: {}
    Bot:
      title: Bot
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum:
            - bot
        attributes:
          type: object
          required:
            - name
          properties:
            name:
              type: string
      required:
        - id
        - type
        - attributes
      description: Bot
      x-examples: {}
    Metric:
      title: Metric
      type: object
      x-examples: {}
      properties:
        id:
          type: string
          enum:
            - ACTIVE_PEOPLE
            - NEW_VISITORS
            - UNIQUE_VISITORS
            - SUBSCRIBERS
            - UNSUBSCRIBES
            - TOTAL_MESSAGES_SENT
            - ENGAGEMENT_PER_USER
        type:
          type: string
          enum:
            - metric
        attributes:
          type: object
          required:
            - value
            - title
            - date
          properties:
            value:
              type: number
            title:
              type: string
            date:
              type: string
              format: date
      required:
        - id
        - type
        - attributes
    NewExternalActivity:
      title: NewExternalActivity
      type: object
      x-examples: {}
      properties:
        type:
          type: string
          enum:
            - external-activity
        attributes:
          type: object
          required:
            - recipient
            - from
            - messages
          properties:
            recipient:
              type: string
            from:
              type: string
              format: uuid
            messages:
              type: array
              items: {}
      required:
        - type
        - attributes
    ExternalActivity:
      title: ExternalActivity
      allOf:
        - type: object
          properties:
            id:
              type: string
              format: uuid
          required:
            - id
        - $ref: '#/components/schemas/NewExternalActivity'
      x-examples: {}
  securitySchemes: {}
